module.exports = {
   userTypes: ['Admin', 'JobSeeker', 'Company'],
   jobTypes: ['Full Time', 'Part Time', 'Internship', 'Temporary', 'Freelance'],
   states: [
    'AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC',
    'FM', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS',
    'KY', 'LA', 'ME', 'MH', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO',
    'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP',
    'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN',
    'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY',
  ],
  regions: ['Northwest', 'Southwest', 'Midwest', 'Northeast', 'Southeast'],
  jobStatus: ['Applied', 'Rejected', 'Contacted'],
  companyStatus: ['Pending', 'Active', 'Rejected'],
  statesToRegion: {
    // Northwest
    'AK': 'Northwest',
    'CA': 'Northwest',
    'CO': 'Northwest', 
    'HI': 'Northwest',
    'ID': 'Northwest',
    'MH': 'Northwest',
    'MT': 'Northwest',
    'NV': 'Northwest',
    'ND': 'Northwest',
    'OR': 'Northwest',
    'SD': 'Northwest',
    'UT': 'Northwest',
    'WA': 'Northwest',
    'WY': 'Northwest',
    // Southwest
    'AS': 'Southwest',
    'AZ': 'Southwest',
    'FM': 'Southwest',
    'GU': 'Southwest',
    'MD': 'Southwest',
    'NM': 'Southwest',
    'MP': 'Southwest',
    'OK': 'Southwest',
    'PW': 'Southwest',
    'TX': 'Southwest',
    // Midwest
    'IL': 'Midwest',
    'IN': 'Midwest',
    'IA': 'Midwest',
    'KS': 'Midwest',
    'KY': 'Midwest',
    'MI': 'Midwest',
    'MN': 'Midwest',
    'MO': 'Midwest',
    'NE': 'Midwest',
    'OH': 'Midwest',
    'TN': 'Midwest',
    'WI': 'Midwest',
    // Northeast
    'CT': 'Northeast',
    'DE': 'Northeast',
    'DC': 'Northeast',
    'ME': 'Northeast',
    'MA': 'Northeast',
    'NH': 'Northeast',
    'NJ': 'Northeast',
    'NY': 'Northeast',
    'PA': 'Northeast',
    'RI': 'Northeast',
    'VT': 'Northeast',
    'VA': 'Northeast',
    'WV': 'Northeast',
    // Southeast
    'AL': 'Southeast',
    'AR': 'Southeast',
    'FL': 'Southeast',
    'GA': 'Southeast',
    'LA': 'Southeast',
    'MS': 'Southeast',
    'NC': 'Southeast',
    'PR': 'Southeast',
    'SC': 'Southeast',
    'VI': 'Southeast',
  }
};
